const data = {
  products: [
    {
      _id: 1,
      name: "Blush Pink Sofa",
      category: "Furniture",
      image: "/images/img1.jpeg",
      price: 500,
      countInStock: 10,
      numReview: 3,
      brand: "Vinotti",
      rating: 4.7,
      description: "Lovely pink blush sofa",
    },
    {
      _id: 2,
      name: "Blush Pink Table",
      category: "Furniture",
      image: "/images/img2.jpeg",
      price: 200,
      countInStock: 8,
      numReview: 5,
      brand: "Cellini",
      rating: 4.7,
      description: "Aesthetic pink coffee table",
    },
    {
      _id: 3,
      name: "Natural Marble Table",
      category: "Furniture",
      image: "/images/img3.jpeg",
      price: 500,
      countInStock: 7,
      numReview: 2,
      brand: "Jakomo",
      rating: 4.9,
      description: "Natural beige marble table",
    },
    {
      _id: 4,
      name: "Transparent Modern Chair",
      category: "Furniture",
      image: "/images/img4.jpeg",
      price: 50,
      countInStock: 0,
      numReview: 20,
      brand: "Lumiere",
      rating: 4.5,
      description: "Simple transparent chair",
    },
    {
      _id: 5,
      name: "Carrie Plate",
      category: "Tableware",
      image: "/images/img5.jpeg",
      price: 10,
      countInStock: 25,
      numReview: 27,
      brand: "Bellagio",
      rating: 4.3,
      description: "Blue ceramic plate with gold spots",
    },
  ],
};

export default data;
