export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_DELETE_ITEM = "CARD_DELETE_ITEM";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";
export const CART_EMPTY = "CART_EMPTY";
